language: ruby
before_install:
  - gem install bundler # the default bundler version on travis is very old and causes 1.9.3 build issues
rvm:
  - jruby
  - rbx
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
